# Generated by Django 3.0.8 on 2020-07-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('usn', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=25)),
                ('marks', models.IntegerField()),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
